pub(crate) mod deepseek;
#[cfg(not(target_arch = "wasm32"))]
pub(crate) mod gigachat;
pub(crate) mod mock;
pub(crate) mod openai;
pub(crate) mod openrouter;
pub(crate) mod xrouter;
#[cfg(not(target_arch = "wasm32"))]
pub(crate) mod yandex;
pub(crate) mod zai;

pub use deepseek::DeepSeekClient;
#[cfg(not(target_arch = "wasm32"))]
pub use gigachat::GigachatClient;
pub use mock::MockProviderClient;
pub use openai::OpenAiClient;
pub use openrouter::OpenRouterClient;
pub use xrouter::XrouterClient;
#[cfg(not(target_arch = "wasm32"))]
pub use yandex::YandexResponsesClient;
pub use zai::ZaiClient;
