fmt:
    cargo fmt --all

clippy:
    cargo clippy --all-targets --all-features -- -D warnings

test:
    cargo test --all-features

run:
    cargo run -p xrouter-app

run-billing:
    cargo run -p xrouter-app --features billing
