"""Common models for provider API.

This module contains models that are used across different parts of the provider API,
such as response types, usage statistics, and token counting.
"""
from enum import Enum
from typing import Optional

from pydantic import BaseModel, Field


class ResponseType(str, Enum):
    """Response type constants."""

    CHAT_COMPLETION = "chat.completion"
    CHAT_COMPLETION_CHUNK = "chat.completion.chunk"


class CompletionTokensDetails(BaseModel):
    """Breakdown of tokens used in a completion."""

    accepted_prediction_tokens: Optional[int] = Field(
        None,
        description=(
            "When using Predicted Outputs, the number of tokens "
            "in the prediction that appeared in the completion"
        ),
    )
    audio_tokens: Optional[int] = Field(
        None,
        description="Audio input tokens generated by the model",
    )
    reasoning_tokens: Optional[int] = Field(
        None,
        description="Tokens generated by the model for reasoning",
    )
    rejected_prediction_tokens: Optional[int] = Field(
        None,
        description=(
            "When using Predicted Outputs, the number of tokens "
            "in the prediction that did not appear in the completion. "
            "However, like reasoning tokens, these tokens are still "
            "counted in the total completion tokens for purposes "
            "of billing, output, and context window limits"
        ),
    )


class PromptTokensDetails(BaseModel):
    """Breakdown of tokens used in the prompt."""

    audio_tokens: Optional[int] = Field(
        None,
        description="Audio input tokens present in the prompt",
    )
    cached_tokens: Optional[int] = Field(
        None,
        description="Cached tokens present in the prompt",
    )


class Usage(BaseModel):
    """Usage statistics for the completion request."""

    prompt_tokens: int = Field(..., description="Number of tokens used in the prompt")
    completion_tokens: int = Field(
        ..., description="Number of tokens used in the completion"
    )
    total_tokens: int = Field(
        ..., description="Total number of tokens used (prompt + completion)"
    )
    completion_tokens_details: Optional[CompletionTokensDetails] = Field(
        None,
        description="Breakdown of tokens used in a completion",
    )
    prompt_tokens_details: Optional[PromptTokensDetails] = Field(
        None,
        description="Breakdown of tokens used in the prompt",
    )
    cost: Optional[float] = Field(
        None,
        description=(
            "Cost of the request in provider's currency. "
            "This field is for OpenRouter compatibility and "
            "will always be None in our implementation."
        ),
    )
