"""Response models for chat completion functionality."""
from typing import Dict, Literal, Optional

from pydantic import BaseModel, Field

from .common import Usage
from .messages import AssistantMessage

FinishReason = Literal[
    "stop", "length", "content_filter", "tool_calls", "blacklist", "error"
]


class Choice(BaseModel):
    """Base choice model for chat completion responses."""

    index: int = Field(description="The index of the choice in the list of choices")
    finish_reason: Optional[FinishReason] = Field(
        None,
        description=(
            "The reason the model stopped generating tokens. Can be: 'stop', 'length', "
            "'content_filter', 'tool_calls'"
        ),
    )
    logprobs: Optional[Dict] = Field(
        None, description="Log probability information for the choice"
    )


class StreamChoice(Choice):
    """Choice model for streaming responses containing delta updates."""

    delta: Optional[AssistantMessage] = Field(
        description="A chat completion delta generated by streamed model responses"
    )


class NonStreamChoice(Choice):
    """Choice model for non-streaming responses containing complete messages."""

    message: AssistantMessage = Field(
        description="A chat completion message generated by the model"
    )


class BaseResponse(BaseModel):
    """Base response model for chat completions."""

    created: int = Field(description="Creation timestamp (Unix timestamp)")
    model: str = Field(description="Model used for generation")
    system_fingerprint: Optional[str] = Field(
        None, description="Optional system fingerprint"
    )
    usage: Optional[Usage] = Field(None, description="Token usage information")


class FullResponse(BaseResponse):
    """Complete response model for non-streaming chat completions."""

    object: str = Field("chat.completion", description="Type of the response object")


class StreamChunk(BaseResponse):
    """Chunk response model for streaming chat completions."""

    object: str = Field(
        "chat.completion.chunk", description="Type of the response object"
    )
