"""Billing-related models."""
from datetime import datetime
from typing import Dict, Optional

from pydantic import BaseModel, Field, ValidationInfo, field_validator

from .common import Currency


class TokenCount(BaseModel):
    """Token count for a specific operation."""

    input: int = Field(..., description="Number of input tokens")
    output: int = Field(..., description="Number of output tokens")
    total: int = Field(..., description="Total number of tokens")
    model: str = Field(..., description="Model used for token counting")
    provider: str = Field(..., description="Provider ID that processed the request")

    # Cached tokens fields
    cache_hit: int = Field(
        default=0,
        description="Number of tokens retrieved from the cache for this request",
    )
    input_cached: bool = Field(
        default=False,
        description=(
            "Flag indicating whether the input was cached "
            "(cache_control was present)"
        ),
    )

    # Output token details
    output_reasoning: Optional[int] = Field(
        None, description="Number of tokens generated by the model for reasoning"
    )

    # Additional metadata (for provider-specific information like cost)
    meta_info: Optional[Dict] = Field(
        None, description="Additional metadata such as openrouter cost"
    )

    @field_validator("total")
    @classmethod
    def validate_total(cls, v: int, info: ValidationInfo) -> int:
        """Ensure total matches sum of input and output."""
        data = info.data
        if "input" in data and "output" in data:
            expected = data["input"] + data["output"]
            if v != expected:
                msg = (
                    f"Total tokens {v} does not match sum of "
                    f"input ({data['input']}) and output ({data['output']})"
                )
                raise ValueError(msg)
        return v


class Payment(BaseModel):
    """Payment information."""

    transaction_id: str = Field(..., description="Unique transaction identifier")
    amount: float = Field(..., description="Payment amount")
    currency: str = Field(..., description="Payment currency")


class PaymentResponse(BaseModel):
    """Response for payment processing."""

    status: str = Field(..., description="Payment status")
    current_balance: float = Field(..., description="Updated balance after payment")
    transaction_id: str = Field(..., description="Transaction identifier")
    processed_at: datetime = Field(..., description="Payment processing timestamp")


class Cost(BaseModel):
    """Cost calculation for token usage."""

    amount: float = Field(
        ..., description="Total cost amount", json_schema_extra={"format": "decimal"}
    )
    currency: Currency = Field(default=Currency.RUB, description="Currency of the cost")
    breakdown: dict[str, float] = Field(
        ...,
        description=(
            "Cost breakdown by component:\n"
            "- prompt: Cost for input tokens\n"
            "- completion: Cost for output tokens\n"
            "- commission: Additional commission amount\n"
            "- cache_discount: Overall savings from caching\n"
            "- cache_hit: Cost of tokens retrieved from cache\n"
            "- cache_write: Cost for writing tokens to cache"
        ),
        json_schema_extra={
            "format": "decimal",
            "examples": [
                {
                    "prompt": "0.15",
                    "completion": "0.25",
                    "commission": "0.05",
                    "cache_discount": "0.03",
                    "cache_hit": "0.10",
                    "cache_write": "0.07",
                }
            ],
        },
    )
    meta_info: Optional[Dict] = Field(None, description="Additional metadata")


class Balance(BaseModel):
    """User balance information."""

    user_id: str = Field(..., description="User ID in the system")
    current_balance: float = Field(
        ..., description="Current balance", json_schema_extra={"format": "decimal"}
    )
    credit_limit: float = Field(
        default=500.00,
        description="Maximum allowed credit",
        json_schema_extra={"format": "decimal"},
    )
    total_spent: float = Field(
        default=0.00,
        description="Total amount spent",
        json_schema_extra={"format": "decimal"},
    )
    last_payment: Optional[float] = Field(
        None, description="Last payment amount", json_schema_extra={"format": "decimal"}
    )
    last_payment_date: Optional[datetime] = Field(
        None, description="When the last payment was made"
    )
    on_hold: float = Field(
        default=0.00,
        description="Amount currently on hold (e.g., for pending transactions)",
        json_schema_extra={"format": "decimal"},
    )
